/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */
import * as Hapi from '@hapi/hapi'
import { eventConfigs } from '@countryconfig/events'
import { sendInformantNotification } from '../notification/informantNotification'
import { ActionConfirmationRequest } from '../registration'
import {
  aggregateActionDeclarations,
  deepMerge,
  getPendingAction
} from '@opencrvs/toolkit/events'
import {
  causeOfDeathFields,
  extractCodFields,
  getSpcCompatibleEventDocument,
  sendRecordToSpcPortal
} from '../spc-coding/utils'

export function getEventsHandler(_: Hapi.Request, h: Hapi.ResponseToolkit) {
  return h.response(eventConfigs).code(200)
}

export async function onCustomActionHandler(
  _: ActionConfirmationRequest,
  h: Hapi.ResponseToolkit
) {
  return h.response().code(200)
}

export async function onCorrectionHandler(
  request: ActionConfirmationRequest,
  h: Hapi.ResponseToolkit
) {
  const event = request.payload
  const eventActions = event.actions

  const pendingAction = getPendingAction(eventActions)
  const correctionDeclaration = pendingAction.declaration

  const correctionsToCauseOfDeathFields = extractCodFields(
    correctionDeclaration,
    causeOfDeathFields
  )

  if (Object.keys(correctionsToCauseOfDeathFields).length === 0) {
    console.log('No corrections to cause of death fields found')
  } else {
    // Below logic should only run if a registrar
    // has made a correction to any of the antecedent
    // cause of death symptoms, meaning that a new
    // UCCode should be generated by the SPC Mortality Portal group
    console.log('Found corrections to cause of death fields')

    const mergedDeclaration = deepMerge(
      aggregateActionDeclarations(event),
      correctionDeclaration
    )

    const spcCompatibleEventDocument = getSpcCompatibleEventDocument(
      event,
      mergedDeclaration
    )

    await sendRecordToSpcPortal(spcCompatibleEventDocument)
  }

  return h.response().code(200)
}

/**
 * This catch-all action route will receive event actions with `Content-Type: application/json`
 */
export async function onAnyActionHandler(
  request: ActionConfirmationRequest,
  h: Hapi.ResponseToolkit
) {
  const token = request.auth.artifacts.token as string
  const event = request.payload

  await sendInformantNotification({ event, token })

  return h.response().code(200)
}
