# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 11.11.11.11 - Target staging server's IP address
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # In most cases these should be left empty, as the VPN server should be the only source of traffic.
    # OpenCRVS should never be exposed to the public internet. If this is not possible to organise,
    # then this should always be set when configuring a production server if there is no other firewall in front of the server.
    # BE CAREFUL! This will block all SSH traffic except from the IP addresses listed here.
    only_allow_access_from_addresses:
      # If you are using a jump server to access this environment, place the IP address of the jump server or other explicitly allowed traffic sources here
      #- 55.55.55.55 # example jump server IP address
      []
    # "enable_backups" is set to false on staging.  Staging will not backup it's own data.
    enable_backups: false
    # "periodic_restore_from_backup" restores daily production backups to your staging server.
    # For this you need to first setup a backup environment
    periodic_restore_from_backup: true
    backup_server_remote_source_directory: /home/backup/backups
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: pankaj
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL23KrPmFT6tZxR5d7dsTybtDf5j9DWzJcoR/Y7iJfL6 github
        state: present
        sudoer: true
      - name: euan
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDECqHO65UpyrrO8uueD06RxGaVVq22f152Rf8qVQQAAIGAMu6gCs7ztlZ8a3yQgSEIjM/Jl1/RqIVs6CziTEef74nLFTZ5Ufz3CLRVgdebBeSBEmhTfTUV0HLkSyNzwKFpuzJxucGd72ulPvEp6eHvyJAPJz37YcU8cjaL1v05T6s2ee99li35GlDDtCzfjVV4ZPAg5JdfWuTj41RAVC0LQhk2/NB4qEu37UxGGjhRFSjBEsS5LxI9QfvgrsHpl/VOn+soH7ZkK7kS6qRgNP/uYsXRWXhHaamcl5OX68gJWTbrW6c7PCqlbCWGnsHJswCmqPIthwXXMfC7ULDNLSKG6mslAt5Dyc8/MCr3vTW7pDyr2d0FvvY86SMQUggxv3qF7TZewqfX1bhK0fMLarIxVMQ1RFo//wN9QGA+2we8rxd2Y1Kr1DBuJyuwXPfv+Exo8yNYQ+x/AYH5k6UVcSYuaB8eYmplG2KQCxt8RBFtoChrwOKNRWLqXdKyfpdp5XmnnWxPvR95gf3h3yLocVYkF0i0uvKKJ0vt8J0Ezfkdfow0B1kUg5bPXKJROX7PwbaCPdYcxyDaO6wwOigRnSmoFvkH1pLb4j1RQAXcX531CHgfN6Izi/h0mpMS4bnyIUcv2GQr+h4z4TxcCtj7qpH2y6yw7XG12jVh7TfeesXG2Q== euanmillar77@gmail.com
        state: present
        sudoer: true
      - name: barry
        ssh_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICw4vvV33xxrTzxAiPoRhuwyWUzmgrP5NPo2n4bmKx7P
        state: present
        sudoer: true
      - name: josh
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDnx9Ths5yQ+Rn0Y+tsIFiO97aRlt93pHLbUstOSGeOKDXGyLUziNWlkBBShSlq1cx4S9nek52V4SVOQgROlyt2BWLw0oCsS6focBsf4WAD1heTjGSUsDCCxkviQCc/kPN0McO3e1IZyeMX6/0n6FF373bAvQYBZMcmA4tUKp5A2hRJldo/q8SIQf2ooehnHKhZJBZyv48BojqEwjRrdEEUhv7W3CQr9J0WDpf+PSe16KYk4HqH1DRKiXJtwgMzMxeXPx5qVBEuaL8KY/fD6GQV3CcBT4s0mdCWX+cSZKzX1rm34V6DW8Rd5fvVAXLyGmlXVXiOjpyNCOEB6ZuQL6bRARd5DmvjXWIwlf8EXzDAgqwsEbXBLRif9noFNMhb1OOOXIfnGjpjZzCVKMLynEqEF/cUpL4GCRxAJRwalcchhjtIyv88C5Vl4nDY0w55pdS/oaJx0KqCkqRQgyVYoEMe3fEDMXEUoAzFvsufUM3RMBu2YLV/8kLyvHxvRJuO7MbAScIUr1nG2N0tRCrgCNpoF/t15hkUhEnxTYZVyLfPni5XnwaKVqpbi5zQgXB/Ctd7i+9WiRa/qGhx7l+T0lz2X9rWoDIXky8cZ2xQYNfaMG3PKldjfawXwN32EOhWjlsoIzgPFLsK4QYqIMZcgpLTla1gBNJuxJUOuQe3vhMJDQ== MackBook-M3M
        state: present
        sudoer: true
      - name: siya
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCx/Htkb/OF5xHpJwvrNnVcShvW2JgeYhdSgjRBKXnxkswHHrrGd1hRJARWqoZ3dMtOa1VBWtYrEDLXuA5wxLSBKMX9yn15I7wZ9gz237SErZEQSJrKtC+XNRGaV6P2QbZFpBN4xpuxIxuiOCv1bp3xPLfcnKer9bL6nnx/ao1IKfw4BluhJ3AFg1t5iH8YNoiUcNs33Ma+TilKiETMx3VR+vsu4CW5klSg3zxCRwU5GI/H27R6xq/HcCvDIudqMRawj5cG9gUfLexCLa2ci+g5EhhldEgrHp9Whng/pzrLTmM5SE+vXM/XPp3Bza9PgO5oqN5iQBgUlbCMQ4y+piZier/F3Z3K4FDXmMFmraXaO+7gESJ6KZifMdWKlxSBcXD47pabyzKiqHNWn7/XnHJvu5Vv7+6DY3mIMB1/bxtlC3NG3UCcsdf8Yfifzq5PwuTR1eUTcz5QgpcsPFT64qWQSNKyud6v/te2msOZ5AN02Pf0vGXMyGLMekdAtXt7+Y+GXsZqYuvRPsO5VPl7Tf6c3k3gLYZsDEgVmVskMplb9ATHZBTrph28OnbLxFKPvWPucdD4wA39iP/QyZRj+EpYn5hDPu+KGZAv4ZPdGysGCeHaYALQzfSaQroNZlZStjQp5hw8ut6k+PinrSb7Jx0P/Y9mzZ+AUo98Jbjn+Inemw== siya@opencrvs.org
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    pankaj-staging: # @todo set this to be the hostname of your target server
      ansible_host: '138.199.211.183' # @todo set this to be the hostname of your target server
      data_label: data1
      # If you are using a jump server to access this environment, enter other SSH args here.
      # ansible_ssh_common_args: '-J jump@55.55.55.55 -o StrictHostKeyChecking=no' # @todo set this to be the IP address of your jump server

# This staging servers is configured to only use one server
docker-workers: {}

# For staging server to be able to restore from backups, it needs to have access to the backup server.
# @todo if you do not intend to set up automatic sync from the backup server, you can remove this section.
backups:
  hosts:
    pankaj-backup: # @todo set this to be the hostname of your backup server
      ansible_host: '162.55.183.184' # set this to be the IP address of your backup server
      # Written by provision pipeline. Assumes "backup" environment
      # exists in Github environments
      ansible_ssh_private_key_file: /tmp/backup_ssh_private_key
# If you are using a jump server to access this environment
# jump:
#   hosts:
#     your-jumpserver-hostname-here: # @todo set this to be the hostname of your backup server
#       ansible_ssh_private_key_file: /tmp/jump_ssh_private_key # Written by provision pipeline. Assumes "jump" environment exists in Github environments
#       ansible_host: '55.55.55.55'
